version: '3.9'

services:
  mongo:
    image: mongo:6.0
    container_name: knowledge-mongo
    restart: always
    ports:
      - '27018:27017' #host_machine's port:docker's port
    environment:
      MONGO_INITDB_DATABASE: knowledge
    volumes:
      - mongo-data:/data/db
    networks:
      - knowledge-network  
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: knowledge-backend
    restart: always
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env.example
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    networks:
      - knowledge-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: knowledge-frontend
    restart: always
    ports:
      - '5173:80'
    env_file:
      - ./frontend/.env.example
    depends_on:
      - backend
    networks:
      - knowledge-network

volumes:
  mongo-data:

networks:
  knowledge-network:
    driver: bridge
